### ISSUE TITLE
Post actions click behavior error

### ISSUE THREAD

**Issue by mustafaer** [ozziest/tinyblog#11]
Every click on the marked areas on the following photos, acting like router change. This action being problem when clicked to back action operation on browser.

![Screenshot 2024-11-19 at 00 36 28](https://github.com/user-attachments/assets/581acae7-afb9-497c-9529-46271b755d47)
![Screenshot 2024-11-19 at 00 37 02](https://github.com/user-attachments/assets/3bc687bc-e3ea-4211-8700-445ae91b3750)

**Comment by ozziest** [comment]
Clicking the username should redirect to the profile page. Also, the reply count should redirect to the post detail. 

But the view count button should use `preventDefault` function. Later we are going to add a modal for stats.

**Comment by mustafaer** [comment]
I think I gave too little detail about the bug. When these fields are clicked repeatedly, they are entered as a new record in the router. So when I try to go back, I have to do more than 1 back click.

**Comment by ozziest** [comment]
@mustafaer interesting. I'll check it.
