### ISSUE TITLE
initialTextState not updated when I clicked a hashtag

### ISSUE THREAD

**Issue by akseyh** [ozziest/tinyblog#29]
https://github.com/ozziest/tinyblog/blob/97cad02c75c642f5fec2ba5f73ed21a047fb62c5/app/src/views/TagsView.tsx#L17

![1119](https://github.com/user-attachments/assets/6e45ac4f-037b-43a9-8296-ea0581f9b760)

**Comment by ozziest** [comment]
@akseyh thanks for the feedback. 🤗
