### ISSUE TITLE
Unnecessary GET /me request

### ISSUE THREAD

**Issue by hanifisenturk** [ozziest/tinyblog#34]
Hi!  

I noticed that when I visited the **https://tinyblog.space/about** page, a GET request was sent to the `/me` endpoint, but the response returned a 401 error. This request shouldn’t be sent on this page.

**Comment by ozziest** [comment]
Hey! Thanks for the feedback. ☺️ 

I think that is a necessary request to understand if the user has a valid session or not. But yes, we don't use that data on about page yet. But we might implement some features (maybe user's avatar on somewhere) in future. ☺️
